export const productos = [
    { producto: "Descuentos" },
    { producto: "Navidad" },
    { producto: "Promociones" },
    { producto: "Electro hogar" },
    { producto: "Tecnología" },
    { producto: "Mujer" },
    { producto: "Hombre" },
    { producto: "Accesorios Moda" },
    { producto: "Muebles y Organizacion" },
    { producto: "Dormitorio" },
    { producto: "Niños y juguetes" },
    { producto: "Zapatos" },
    { producto: "Deportes al aire libre" },
    { producto: "Bellleza y salud" },
    { producto: "Cocina y masaje" },
    { producto: "Baño" },
    { producto: "Supermercados" },
    { producto: "Bebés" },
    { producto: "jardín e iluminacion" },
    { producto: "Mascotas" },
    { producto: "Automotriz" },
    { producto: "Herramienta y maquinaria" },
    { producto: "Construcción" },
    { producto: "Pisos, pinturas y terminaciones" },
    { producto: "Ferreteria" },
    { producto: "Productos Internacionales con envio gratis" },
    { producto: "Otras categorias" },
    { producto: "Emprendedores" }
];
